### ISSUE TITLE
[Feature] Add option to follow playback in playlist view

### ISSUE THREAD

**Issue by ripdog** [ludouzi/fooyin#102]
Currently, there doesn't seem to be a way to easily find the currently playing song in the playlist view. With a very large playlist, this is a serious issue! Especially as the song info view only displays info on the selected song, not the playing song.

As such, a feature to auto-select the currently playing song in the currently playing playlist would be nice.

Ideally, this function could be located in a menu so that it can be easily toggled. Perhaps in the playback menu?

**Comment by ludouzi** [comment]
Cursor follows playback is already an option in the playlist settings page under behaviour: 

![Screenshot_2024-05-19_13 33 56](https://github.com/ludouzi/fooyin/assets/45490980/2f175d6b-52ca-44e2-895c-dd1a1dc951ff)

If you're talking about an option to scroll to the currently playing track outside of the track changing (manually), I've been planning to add that. I'm thinking of adding middle-click, double-click actions to the playlist tabs to make it easy to do so. I can throw it in a menu somewhere as well.

**Comment by ripdog** [comment]
I had a feeling this option would already exist. It seemed so obvious.
Thanks for the handholding 😭

Still, I feel like it would be worth adding as a menu option.

**Comment by ludouzi** [comment]
No worries!

I'll add it to the playback menu at some point. And the option to scroll to the current track on demand.
