### ISSUE TITLE
[Feature Request] Add Library View Selection Playlist

### ISSUE THREAD

**Issue by erin-desu** [ludouzi/fooyin#107]
Foobar2000 has a feature to enabled Library View Selection Playlist which creates a dynamic (?) playlist from currently selected thing in library. Eg. I can choose a directory in a tree (or album, depends on sorting) and it updates the Library View Selection Playlist.

**Comment by ludouzi** [comment]
This is already supported, though rather than a global setting/selection playlist, it's an individual option for the Library Tree and Library Filters:

![image](https://github.com/ludouzi/fooyin/assets/45490980/7f20e208-dcbc-4aeb-8d68-d0117abb00fd)

**Comment by erin-desu** [comment]
Thanksies ^^
