### ISSUE TITLE
[Feature request]: Option to avoid resampling and change audio backend directly to ALSA output, even if Pipewire is present too

### ISSUE THREAD

**Issue by marek-lach** [ludouzi/fooyin#119]
It would be a good idea to have the option (for lossless music collectors) to avoid system resampling (down sampling, which e.g. PipeWire does by default) of audio files. In relation to this, there could be an option to explicitly customize/change audio backend to alsa outputing directly to the sound card).

Thank you for considering,
M -

**Comment by ludouzi** [comment]
Agreed. Selecting a hardware device for the ALSA output is on my to-do list. I'll get around to it soon.

Oh, and thanks for the sponsor!

**Comment by marek-lach** [comment]
> Agreed. Selecting a hardware device for the ALSA output is on my to-do list. I'll get around to it soon.

Thanks!
