### ISSUE TITLE
Sort playlist based on current order, not the db/global(?) order

### ISSUE THREAD

**Issue by Nate-Sheibley** [ludouzi/fooyin#126]
Right now, if I sort my playlist any given operation always results in the exact same result. 
This may be desired behavior, but rn there is no way to sort albums in track order with metadata.

Action:
Sort by track no. 
Then sort by album/artist.

Current behavior:
Playlist is sorted by track, all tracks 1s then all track 2s etc.
Sorting playlist by album results in scrambles track order. eg [4, 2, 10, ...] 
I can not see the value it's using to pick this order.

Expected behavior:
Playlist is sorted by track, all tracks 1s then all track 2s etc.
Then this order is then input to the sort by album/artist.
Resulting album/artist being the primary grouping, and track no. being in order inside them.

**Comment by ludouzi** [comment]
This is not desired behaviour actually.

On startup, all tracks are loaded from the db and sorting according to the script in Settings->Library->Sorting. When sorting on a playlist column, it only considers that column value, overriding the previous sort string.

For sorting on a common field like album, there's going to be a lot of tracks with identical sort strings. The issue in this case is that the function used for sorting is not guaranteed to be stable, meaning the original order of tracks may be lost.

The solution for this is to use std::stable_sort, which guarantees the original order for identical values. It's potentially less efficient, but I haven't seen any issues after testing, so I'll switch all track sorting over to it.

**Comment by Nate-Sheibley** [comment]
Thanks for the note. It's a departure from foobar2k function so I wasn't sure

Really hoping collaborator plugin support takes off like foobar2k. A few folks on my distro's forum have appreciated me sharing it already. Wish I knew C++ to contribute, but I've got my hands too full to learn another language rn.
