### ISSUE TITLE
[Feature Request] Album Artist should fall through to Artist

### ISSUE THREAD

**Issue by dalto8** [ludouzi/fooyin#130]
Currently, when Album Artist is not populated most views which contain Album Artist produces strange results.

For example, the Album Artist filter places them all under "?" and the playlist shows them as "Unknown Artist" which may cause the sort to be different than what is expected.

Ideally, when Album Artist is empty, it would use Artist which would provide a more consistent experience.

**Comment by ludouzi** [comment]
Great idea. I've just pushed a commit which provides fallbacks for the following fields:

**Album Artist**: Artist, Composer, Performer
**Artist**: Album Artist, Composer, Performer
**Title**: Filename

**Comment by dalto8** [comment]
Thanks!
