### ISSUE TITLE
Thank you

### ISSUE THREAD

**Issue by vod3** [ludouzi/fooyin#132]
Just wanted so say thanks for this awesome piece of software, you casually cured my year-long search for the perfect music player. The Folder View, the customizable Interface, the little things like saving a layout...

Great Work!

**Comment by ludouzi** [comment]
Thank you! 

It means a lot that so many people are choosing to use fooyin, even at this early stage of development. There's a lot of work ahead, and comments like this inspire me to keep going. Hopefully, for many years to come.
