### ISSUE TITLE
Seekbar doesn't stop when track is paused

### ISSUE THREAD

**Issue by miged** [ludouzi/fooyin#133]
Version: 0.4.4 (flatpak)

When you press pause while a track is playing, the seekbar will keep moving as if the track is still playing. This happens with the regular and waveform seekbar.

**Comment by ludouzi** [comment]
I can reproduce this in the flatpak package, but only for the ALSA output. Looking into it now.

**Comment by miged** [comment]
Updated to the newest version and that fixed it. Thanks!
