### ISSUE TITLE
FLAC files

### ISSUE THREAD

**Issue by LukeZBaker** [ludouzi/fooyin#41]
Track lengths don't appear with FLAC files. It's also not possible to use the playback slider with FLACs.

**Comment by ludouzi** [comment]
My library is comprised of mostly FLAC and I haven't seen such an issue yet. Would you be able to share a file you're having problems with? I'm thinking it may be metadata related.

**Comment by LukeZBaker** [comment]
It's happening with every FLAC I tried. Maybe it's an issue with my setup under Manjaro. I will test more.

**Comment by ludouzi** [comment]
Very unusual. Which version of TagLib do you have installed? Do they play fine in other music players?

**Comment by LukeZBaker** [comment]
I've got version 1.13.1 of TagLib installed (it's the version in the Official Repositories in Manjaro).

I have tested the vast majority of Linux music players. All my FLAC files play fine in other players.

**Comment by ludouzi** [comment]
Thanks, I've managed to reproduce it. Looks like I missed a few things when adding support for TagLib 2.0.
