### ISSUE TITLE
Installing fooyin

### ISSUE THREAD

**Issue by LukeZBaker** [ludouzi/fooyin#42]
I was able to build the AUR package for fooyin after creating some symbolic links to the shared libraries, but I failed to build the program under Ubuntu.

Are there any plans to create a deb package? Or a cross-Linux platform snap, AppImage, Flatpak?

BTW I like fooyin. The fact you've already implemented gapless playback is a credit to you!

**Comment by ludouzi** [comment]
I've only just noticed the AUR package, so thanks for letting me know. After a quick glance, the package installing everything manually is the problem. I'll get in contact with the maintainer to try and get it fixed.

It builds fine for Ubuntu in the CI, but I'll test it myself in a VM in a bit. As for packaging, there is a plan to provide packages for release v0.5 onwards, and I'm currently looking into the best way to do that.

And I'm glad you like it! Fooyin started as just a small project for developing my skills after graduation, and it means a lot that other people use it.

**Comment by LukeZBaker** [comment]
Thanks so much for making an Ubuntu section in your BUILD.md notes. I have installed v0.3.7 under Ubuntu 23.10 now.

I will publish a short update to my review, as I didn't cover things like Obsidian and Ember, or Plugins (as they weren't showing). And track times/slider bar work fine now following your tweak to take into account the older version of TagLib (1.13.1) that Ubuntu (and Manjaro) uses.

**Comment by ludouzi** [comment]
No problem. I'm glad you got it working. I'm currently setting up my CI to package fooyin into a .deb for future releases, so it should be even easier soon.

**Comment by ludouzi** [comment]
I'll close this since packages will now be provided for releases moving forward. An AppImage is also being considered too.
