### ISSUE TITLE
Playing icon

### ISSUE THREAD

**Issue by LukeZBaker** [ludouzi/fooyin#50]
Play a track from any view. It shows a playback triangle icon with the playing track highlighted.

Change the view, and this triangle and highlighing isn't displayed until the next track starts.

Is this by design?

**Comment by ludouzi** [comment]
Nope, good catch! It should now show correctly with https://github.com/ludouzi/fooyin/commit/f64d4bafe2bf6c2f3a7d6ee227cf3edfc550c857.
