### ISSUE TITLE
Multi-column mode

### ISSUE THREAD

**Issue by LukeZBaker** [ludouzi/fooyin#51]
(Personally I think the multi-column mode should be on by default).

When using the multi-column mode, the playback icon isn't shown. 

There are bugs with the background highlighting of the current track, sometimes the track column of the current playing track is darker than the background colour of the other columns.

![multi-column-mode](https://github.com/ludouzi/fooyin/assets/42400104/e50f2067-5323-486e-9004-6a12dfe5cd61)

The darker background column persists when we move on to the next track.

![multi-column-mode1](https://github.com/ludouzi/fooyin/assets/42400104/b24a32dd-bac8-499e-9dc4-faf93b572e08)

**Comment by ludouzi** [comment]
I've now made multi-column mode the default playlist view, with an option to switch to single-column mode in the context menu. I've also changed the default playlist preset to 'Track Table' as it more closely resembles how most Linux players layout their playlists.

![Screenshot_20240302_212053](https://github.com/ludouzi/fooyin/assets/45490980/5ab44636-0301-4f31-ac39-11ca10fbf57a)

Closing this for now.
