### ISSUE TITLE
Layout issue

### ISSUE THREAD

**Issue by LukeZBaker** [ludouzi/fooyin#67]
Here's a bug

Make changes to a layout, then export it. I can see the layout file in the ~/.config/fooyin/layouts directory and the new entry appears in Quick Setup.

But choosing that new entry doesn't load it (you can see it doesn't get loaded by switching to a different layout e.g. Simple and then back to the newly saved layout).

Also, if I try to import the newly created layout it doesn't get loaded.

BTW I love the new functionality; I wrote a quick write-up on v0.4.0.

**Comment by ludouzi** [comment]
Definitely a bug. I'll look into it.

As a heads up, I'm going to be changing the structure of layout files to incorporate a version number as well as optional window size information, so don't rely on any saved layouts working after then. I'll guarantee backwards compatibility after that though.

And thanks for the updated review! It's great to hear such positive feedback early in development.
