### ISSUE TITLE
Feature Request: Playlist Tabs

### ISSUE THREAD

**Issue by ripdog** [ludouzi/fooyin#83]
It would be fantastic if the playlist view could optionally expose a tab bar on it's top, to easily switch playlists without having to keep a dedicated, vertical panel open for this task. 

Also, it would be nice if a new playlist button was included!

**Comment by ludouzi** [comment]
That's already an option - in layout editing mode it's a widget under splitters (Playlist Tabs). 

I'll add an option to toggle a new playlist button, as I agree that would be useful.

**Comment by ripdog** [comment]
Ack! You're quite right, I missed that. Thanks.
