### ISSUE TITLE
Job 1, 'fooyin' terminated by signal SIGSEGV (Address boundary error) when trying to add folders or music 

### ISSUE THREAD

**Issue by 1999masih** [ludouzi/fooyin#88]
hi. I get this error when i try to add music folders in fooyin. 
`Job 1, 'fooyin' terminated by signal SIGSEGV (Address boundary error)`
I am using arch kde plasma 6 wayland.

**Comment by ludouzi** [comment]
How are you running fooyin? Are you using one of the packages in the AUR, or are you running from a master build?

**Comment by 1999masih** [comment]
I am using fooyin-bin package from aur.

**Comment by 1999masih** [comment]
thanks!
